repos:
  # --------------------
  # General hygiene
  # --------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        files: ^backend/
      - id: trailing-whitespace
        files: ^backend/
      - id: check-yaml
        files: ^backend/
      - id: check-added-large-files
        files: ^backend/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - .secrets.baseline

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        files: ^backend/
        args: [--config, backend/pyproject.toml]
      - id: ruff-format
        files: ^backend/
        args: [--config, backend/pyproject.toml]
