services:
  db:
    image: postgres:16-alpine
    container_name: safetysuite_db
    env_file: ./backend/.env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"    # only dev;
    restart: unless-stopped

  api:
    build: ./backend
    container_name: safetysuite_api
    depends_on:
      - db
    env_file: ./backend/.env
    ports:
      - "6548:8000"
    restart: unless-stopped

  # app:
  #   build: ./frontend
  #   container_name: safetysuite_app
  #   depends_on:
  #     - api
  #   env_file: ./frontend/.env
  #   ports:
  #     - "6549:8000"    # only dev;
  #   restart: unless-stopped


volumes:
  data:
